/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.02.00

  Company:
      Microchip Technology, Inc.
 
  File Name:
     internal_resource_main_color_defines.h
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

#ifndef INTERNAL_RESOURCE_MAIN_COLOR_DEFINES_H_FILE
#define INTERNAL_RESOURCE_MAIN_COLOR_DEFINES_H_FILE

#define BLACK   (0)
#define GRAY   (1)
#define SILVER   (2)
#define TIMBERWOLF   (3)
#define WHITE   (4)
#define FUZZY_WUZZY_BROWN   (5)
#define CHESTNUT   (6)
#define INDIAN_RED   (7)
#define RED_ORANGE   (8)
#define BRICK_RED   (9)
#define MAROON   (10)
#define JAZZBERRY_JAM   (11)
#define MAHOGANY   (12)
#define SUNSET_ORANGE   (13)
#define BITTERSWEET   (14)
#define MELON   (15)
#define VIVID_TANGERINE   (16)
#define OUTRAGEOUS_ORANGE   (17)
#define ULTRA_ORANGE   (18)
#define BURNT_SIENNA   (19)
#define BROWN   (20)
#define SEPIA   (21)
#define BURNT_ORANGE   (22)
#define COPPER   (23)
#define ORANGE   (24)
#define ATOMIC_TANGERINE   (25)
#define CHARTREUSE   (26)
#define BEAVER   (27)
#define RAW_SIENNA   (28)
#define TUMBLEWEED   (29)
#define TAN   (30)
#define DESERT_SAND   (31)
#define FLESH   (32)
#define PEACH   (33)
#define MACARONI_AND_CHEESE   (34)
#define MANGO_TANGO   (35)
#define NEON_CARROT   (36)
#define YELLOW_ORANGE   (37)
#define GOLDENROD   (38)
#define SUNGLOW   (39)
#define DANDELION   (40)
#define YELLOW   (41)
#define GOLD   (42)
#define ULTRA_YELLOW   (43)
#define LASER_LEMON   (44)
#define UNMELLOW_YELLOW   (45)
#define CANARY   (46)
#define GREEN_YELLOW   (47)
#define BANANA_MANIA   (48)
#define PINE_GREEN   (49)
#define TROPICAL_RAIN_FOREST   (50)
#define GREEN   (51)
#define SHADOW   (52)
#define OLIVE_GREEN   (53)
#define FOREST_GREEN   (54)
#define FERN   (55)
#define MOUNTAIN_MEADOW   (56)
#define JUNGLE_GREEN   (57)
#define SHAMROCK   (58)
#define CARIBBEAN_GREEN   (59)
#define ULTRA_GREEN   (60)
#define SCREAMIN__GREEN   (61)
#define YELLOW_GREEN   (62)
#define ELECTRIC_LIME   (63)
#define INCH_WORM   (64)
#define GRANNY_SMITH_APPLE   (65)
#define MAGIC_MINT   (66)
#define SEA_GREEN   (67)
#define SPRING_GREEN   (68)
#define BLUE_GREEN   (69)
#define PACIFIC_BLUE   (70)
#define CERULEAN   (71)
#define ROBIN_S_EGG_BLUE   (72)
#define TURQUOISE_BLUE   (73)
#define BLIZZARD_BLUE   (74)
#define SKY_BLUE   (75)
#define CORNFLOWER   (76)
#define OUTER_SPACE   (77)
#define MIDNIGHT_BLUE   (78)
#define PRUSSIAN_BLUE   (79)
#define NAVY_BLUE   (80)
#define DENIM   (81)
#define BLUE   (82)
#define BLUE_VIOLET   (83)
#define WILD_BLUE_YONDER   (84)
#define INDIGO   (85)
#define MANATEE   (86)
#define BLUE_BELL   (87)
#define CADET_BLUE   (88)
#define PERIWINKLE   (89)
#define PURPLE_HEART   (90)
#define ROYAL_PURPLE   (91)
#define VIOLET__PURPLE_   (92)
#define VIVID_VIOLET   (93)
#define PURPLE_MOUNTAIN_S_MAJESTY   (94)
#define WISTERIA   (95)
#define PURPLE_PIZZAZZ   (96)
#define HOT_MAGENTA   (97)
#define FUCHSIA   (98)
#define PINK_FLAMINGO   (99)
#define SHOCKING_PINK   (100)
#define ULTRA_PINK   (101)
#define ORCHID   (102)
#define EGGPLANT   (103)
#define PLUM   (104)
#define RED_VIOLET   (105)
#define MULBERRY   (106)
#define CERISE   (107)
#define RAZZMATAZZ   (108)
#define RED   (109)
#define TORCH_RED   (110)
#define SCARLET   (111)
#define RADICAL_RED   (112)
#define BRINK_PINK   (113)
#define ULTRA_RED   (114)
#define WILD_WATERMELON   (115)
#define CRANBERRY   (116)
#define VIOLET_RED   (117)
#define WILD_STRAWBERRY   (118)
#define RAZZLE_DAZZLE_ROSE   (119)
#define MAGENTA   (120)
#define SALMON   (121)
#define TICKLE_ME_PINK   (122)
#define CARNATION_PINK   (123)
#define MAUVELOUS   (124)
#define COTTON_CANDY   (125)
#define LAVENDER   (126)
#define PIG_PINK   (127)
#endif

